data:
  train_file: "TRAIN_FILE_PATH"
  val_file: ""
  draw: "segm"

model:
  init_checkpoint: "USE_PRETRAIN4_CKPT"
  transpose_input: True

  num_texts: 4
  image_size: [384, 704]
  patch_size: 16
  spatial_pool_size: 2
  use_bfloat16: True
  vocab_size: 50370
  hidden_size: 768
  resnet_layers: [3, 4, 9]


  attention_probs_dropout_prob: 0.0
  hidden_dropout_prob: 0.1
  hidden_act: "gelu"
  initializer_range: 0.02
  intermediate_size: 3072
  max_position_embeddings: 1024
  num_attention_heads: 12
  num_hidden_layers: 12
  num_vision_transformer_hidden_layers: 12
  num_lang_transformer_hidden_layers: 12

  share_params: True

device:
  use_tpu: True
  num_tpu_cores: 8
  tpu_run_config: None # This will get loaded in
  output_dir: "OUTPUT_DIR"
  train_batch_size: 64
  val_batch_size: 64
  iterations_per_loop: 2500


optimizer:
  type: "adam_optimizer"
  learning_rate: 0.000012
  num_train_steps: 60000 # 18 epochs
  num_warmup_steps: 6000
  weight_decay_rate: 0.01
  beta_2: 0.98
  clip_norm: 0.0
  adafactor: False
  use_bfloat16_adam: True
  verbose: False

  # Anything matching one of the regex conditions will have the parameters overridden.
  param_overrides: [
    [["LayerNorm", "layer_norm", 'GroupNorm', "bias", "batch_normalization"], {"weight_decay_rate": 0}],
  ]

downstream:
  task: "vcr"
  mode: "answer" # "answer" "rationale"

validate:
  eval_samples: 26534
  eval_timeout: 72000